### PR TITLE
Only send www-authenticate for 401. Make realm dynamic.

### PR DESCRIPTION
**Pull request by mcollina**
Following up from https://github.com/fastify/fastify-basic-auth/pull/39#discussion_r628159645, I refactored a good part of the library.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Eomm — APPROVED** [review]

**Comment by crutch12** [comment]
We should update index.d.ts, it is not supported now

**Comment by Uzlopak** [comment]
You mean adding realm() to the typings?

**Comment by Uzlopak** [comment]
Can you provide a PR with a test please?

**Comment by crutch12** [comment]
image

**Pull request merged**
