### PR TITLE
early response on error instead of proceeding with the lifecycle using next

### PR DESCRIPTION
**Pull request by salmanm**

### CODE REVIEW

**Comment by salmanm** [comment]
I think calling `next(err)` would let it continue the request life cycle and eventually land up in the same situation. Wouldn't it?

**Comment by salmanm** [comment]
I suppose in this case (missing auth header), we should be doing an early response from the hook. I don't think the control should ever reach the handler. I did test it locally and found it working. (Unless I've missed some case you're thinking)

I'll add a unit test as soon as we come to a conclusion on this.

**Comment by mcollina** [comment]
> I suppose in this case (missing auth header), we should be doing an early response from the hook. I don't think the control should ever reach the handler. I did test it locally and found it working. (Unless I've missed some case you're thinking)

That's true, right. We shouldn't call `next()` at all.

**Comment by salmanm** [comment]
Added a test to ensure the correct response.

**Comment by salmanm** [comment]
https://www.fastify.io/docs/latest/Hooks/#respond-to-a-request-from-a-hook

> If needed, you can respond to a request before you reach the route handler.

Isn't this a use case of the above pattern? We're in `preHandler` and we don't want the life cycle to be continued because user isn't authenticated. If we let it continue, the custom `setErrorHandler` (if set) kicks in and converts the 401 to 500 response.

**Comment by salmanm** [comment]
Closing as its fixed in https://github.com/fastify/fastify-basic-auth/pull/9

**Pull request closed without merging**
